# Generated by Django 4.2.7 on 2024-02-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(null=True, related_name='posts', to='posts.hashtag'),
        ),
    ]
