version: '3'
services:
  web:
    image: moc/server
    container_name: web
    command: bash -c "while ! nc -z mysql_db 3306; do sleep 1; done && python manage.py makemigrations && python manage.py migrate && gunicorn MoC.wsgi:application -b 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    networks:
      - server
    depends_on:
      - mysql_db

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./media:/media
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - server

  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${db_password} # .env에 있는 db_password와 연결
      MYSQL_DATABASE: moc
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3305:3306"
    networks:
      - server

networks:
  server:

volumes:
  database:
