# Generated by Django 4.2.7 on 2024-02-21 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_on', models.DateField()),
                ('finish_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Weekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_on', models.DateField()),
                ('finish_on', models.DateField()),
                ('monthly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly', to='daily.monthly')),
            ],
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('weekly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily', to='daily.weekly')),
            ],
        ),
    ]
