# Generated by Django 4.2.7 on 2024-02-23 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_daily'),
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuPularPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pupular_post', to='daily.daily')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pupular_post', to='posts.post')),
            ],
        ),
    ]
