# Generated by Django 4.2.7 on 2024-02-23 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_daily'),
        ('daily', '0002_pupularpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PuPularPost',
            new_name='PoPularPost',
        ),
    ]
