# Generated by Django 4.2.7 on 2024-02-23 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_daily'),
        ('daily', '0003_rename_pupularpost_popularpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularpost',
            name='daily',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_post', to='daily.daily'),
        ),
        migrations.AlterField(
            model_name='popularpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_post', to='posts.post'),
        ),
    ]
